"""
Django settings for testproject project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# read closest .env if present
env = environ.Env()
environ.Env.read_env() 


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rys_c9p%0ng!bqsk%px2gda%b)q80u0^ul(yun&2c6ldtc@&v='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_db_backups',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'testproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



# Read DB_TYPE from Environment (Defaults to sqlite for local dev)
DB_TYPE = env('DB_TYPE')

if DB_TYPE == 'postgres':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': env('DB_NAME'),
            'USER': env('DB_USER'),
            'PASSWORD': env('DB_PASSWORD'),
            'HOST': env('DB_HOST'),
            'PORT': env('DB_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


DROPBOX_APP_KEY = env("DROPBOX_APP_KEY")
DROPBOX_APP_SECRET = env("DROPBOX_APP_SECRET")
DROPBOX_REFRESH_TOKEN = env("DROPBOX_REFRESH_TOKEN")

CLOUD_DB_BACKUP = {
    # Storage Configuration
    "BACKUP_DIR": BASE_DIR / "backups",
    
    # Retention
    "RETENTION_MAX_COUNT": 3,
    "RETENTION_MAX_AGE_DAYS": 30,
    
    # Dropbox Credentials (Use ACCESS_TOKEN for simple testing, or the full OAuth flow for production)
    "DROPBOX_FOLDER": "/django-dbbackup",
    
    'STORAGE': 'dropbox',
    'DROPBOX_APP_KEY': DROPBOX_APP_KEY,
    'DROPBOX_APP_SECRET': DROPBOX_APP_SECRET,
    'DROPBOX_REFRESH_TOKEN': DROPBOX_REFRESH_TOKEN,
    
    # Database Binaries (Optional: Only needed if not on system PATH)
    # "PG_DUMP_PATH": r"C:\Program Files\PostgreSQL\16\bin\pg_dump.exe",
    # "PG_RESTORE_PATH": r"C:\Program Files\PostgreSQL\16\bin\pg_restore.exe",
    
    # Docker Support
    "POSTGRES_CONTAINER_NAME": "postgres", 
}


USE_TZ = True


# Configure logging to print detailed info to the console
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django_db_backups': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
